### PR TITLE
New Tools & some neat shell tricks + vim tricks

### PR DESCRIPTION
**Pull request by Albonycal**

### CODE REVIEW

**Review by Albonycal — COMMENTED** [review]
Added shell tricks

**Review by Albonycal — COMMENTED** [review]
added shell trick (grepping for subdomain takeover)

**Review by Albonycal — COMMENTED** [review]
added new tools (acquatone & gau)

**Review by Albonycal — COMMENTED** [review]
Wappalyzer & PwnFox added

**Review by Albonycal — COMMENTED** [review]
added info on inscope by @tomnomnom

**Comment by hakluke** [comment]
awesome thanks!

**Comment by hakluke** [comment]
Hey what's your BC username? We'll send you some swag!

**Comment by Albonycal** [comment]
albonycal
https://bugcrowd.com/albonycal
Thanks!

**Pull request merged**
