### PR TITLE
Update process.md

### PR DESCRIPTION
**Pull request by discodamone**
added recon with mobile apps section

### CODE REVIEW

**Review by hakluke — APPROVED** [review]
Nice tip!

**Comment by hakluke** [comment]
Hey what's your BC username? We'll send you some swag!

**Comment by discodamone** [comment]
> Hey what's your BC username? We'll send you some swag!

Thanks a lot, my username is the same as my github (discodamone). How long does swag usually take to arrive? My shipping address will change at the beginning of May because I'm a college student and will be moving for the summer.

**Comment by hakluke** [comment]
On average: Shipments to US based locations can take 5-10 business days. Internationally, 10-50 business days

**Pull request merged**
