### PR TITLE
Update tools.md

### PR DESCRIPTION
**Pull request by 1-debugger**
Updated as per #17.
Please review @hakluke

### CODE REVIEW

**Comment by Albonycal** [comment]
Hey @tigv1 Everybody's contributions matters.. but should try to at least explain what new is added in this pull request.. I helps the maintainers 
Thank You

**Comment by 1-debugger** [comment]
Hey @Albonycal ,

I guess I have mentioned it in the Description. This is improved version of my previous PR and it's clearly stated in the Description.

Thanks

**Comment by Albonycal** [comment]
K

**Review by hakluke — APPROVED** [review]

**Comment by hakluke** [comment]
thank you!

**Pull request merged**
