### PR TITLE
Update tools.md

### PR DESCRIPTION
**Pull request by tolgahand**

### CODE REVIEW

**Comment by hakluke** [comment]
Yeah, great tools thanks @tolgahand!

**Comment by hakluke** [comment]
Hey what's your BC username? We'll send you some swag!

**Comment by tolgahand** [comment]
Hi @hakluke 

Thank you so much :)

https://bugcrowd.com/Tolgahand

**Comment by tolgahand** [comment]
> Hey what's your BC username? We'll send you some swag!

Hi @hakluke

Thank you so much :)

https://bugcrowd.com/Tolgahand

**Pull request merged**
