### PR TITLE
Using Ctrl keys in shell, ffuf tutorial , tok for creating wordlists & project improvements 

### PR DESCRIPTION
**Pull request by Albonycal**
<3 opensource

### CODE REVIEW

**Review by Albonycal — COMMENTED** [review]
fuzz fast u fool!

**Comment by Albonycal** [comment]
Hey @hakluke I added the bugcrowd support email in the code of conduct.. Change it if you want to.. 
Thank you :)

**Comment by Albonycal** [comment]
Added MIT LICENSE for this project

**Comment by Albonycal** [comment]
CONTRIBUTING.md

**Comment by Albonycal** [comment]
@hakluke any updates? Bounty pls?

**Comment by codingo** [comment]
Hi @Albonycal,

I'm going to close this pull request, mostly because there's a whole lot of unstructured change added here at once making it very difficult to track. To recontribute these changes you'll need to do each section within its own pull request. That's not to say what you have done isn't valuable, it is, but in a cursory review there's quite a bit we'd need to change here (such as other projects being mentioned in contributors.md, and adding your handle into here inappropriately on readme.md, and adding a license type) and the nature of this pull request makes it very difficult to correct in a review cycle.

What I would encourage when working over github is to retain each pull request to a particular task. In this case, I would add the suggestions as one pull request, contributors.md as another, license as another, etc'. If you can do that here we can work changes over each of those independently and then contribute them. If you have questions about that, you can inbox me on twitter (DM's are open) at https://twitter.com/codingo_. And again, thank-you, this is more about keeping the project structured than anything else - it's a good habit to build for github in general.

**Pull request closed without merging**
