### PR TITLE
Adding tip for finding IDOR vulns using Burp match & replace

### PR DESCRIPTION
**Pull request by Healdb**
Just a handy tip that I use to find bugs sometimes, can be useful if the application is sending out lots of requests and you don't have the time/patience to manually check all the endpoints. This way you just use the application naturally and wait to see if any data that isn't yours loads

### CODE REVIEW

**Review by hakluke — APPROVED** [review]
Nice one!

**Comment by hakluke** [comment]
Hey what's your BC username? We'll send you some swag!

**Comment by Healdb** [comment]
Would be great but I already have a bunch of BC swag from my onboarding haha

**Comment by hakluke** [comment]
Haha sorry I didn't check the username, thanks @Healdb !

**Pull request merged**
