### PR TITLE
Add some cool tools 

### PR DESCRIPTION
**Pull request by tamjid0x01**
Add some cool tools for hackers productivity 

1. gau
2. gf 
3. gitleaks
4. gitrob
5. graphql-voyager
6. gron
7. BruteX
8. CT_subdomains
9. Chaos Web
10. GitMiner
11. Gopherus
12. GraphQLmap
13. LinkFinder
14. ParamSpider
15. PayloadsAllTheThings
16. SQLNinja
17. SecLists
18. SecretFinder
19. Sublist3r
20. xsscrapy
21. can-i-take-over-xyz
22. findomain

Thanks 
@tamjid_1971

### CODE REVIEW

**Comment by hakluke** [comment]
Hey, I really love this! Thanks so much for the PR. The only thing I'm concerned about is that there is quite a bit of feature overlap between the tools. I'm trying to keep the tool list extremely curated so that only a shortlist of really great tools are included. 

For example, while subzy is awesome, that functionality is already covered by nuclei, and "can I takeover xyz" is a list not a tool, and those strings are also searched for already by nuclei.

Maybe you could look at narrowing it down a bit?

**Comment by tamjid0x01** [comment]
hey @hakluke , 
Thanks For your  response. 
What can i do now ?

**Comment by Albonycal** [comment]
As he said narrow it down... Remove the tools that have same functionality.. 
Thank You!

**Comment by hakluke** [comment]
Closing due to inactivity - feel free to make the amendments in additional PRs

**Pull request closed without merging**
